apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-fibonacci-service
  labels:
    name: {{ .Release.Name }}-fibonacci-service
    app.kubernetes.io/name: fibonacci-app
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: fibonacci-app-{{ .Chart.Version }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    app.kubernetes.io/name: fibonacci-app
    app.kubernetes.io/instance: {{ .Release.Name }}
