apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-fibonacci-app
  namespace: {{ .Values.monitorNamespace }}
  labels:
    app.kubernetes.io/name: fibonacci-app
    release: {{ $.Release.Name | quote }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: fibonacci-app-{{ .Chart.Version }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      name: {{ .Release.Name }}-consumer
  endpoints:
  - port: metrics 
    interval: 15s
    path: /metrics
